const GITHUB_AUTH_TOKEN = "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"
const BOT_NUMBER = "+94769834458"
const SESSION_ID = "PRABATH-MD~XLAhhZLA#cf3tOIzx8JE8llMy0HGaRfi7coo8U0Lze8yhOnNXJts"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
