const GITHUB_AUTH_TOKEN = "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"
const BOT_NUMBER = "14143633925"
const SESSION_ID = "PRABATH-MD~nMEQ1IJa#OWu7JqECFGvWgmB3QfIUVFcfGd0qESW8g-c-7L6QWbU"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
